### ISSUE TITLE
Create and Initialize the Project

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#1]
- Set up a new MERN stack project with basic folder structure.
- Initialize node project and set _'app.js'_ as the entry point.
- Setup the react app and name it as _'frontend'_

**Comment by ParthDhavan04** [comment]
Hi, I would like to take up this issue.

**Comment by Saga690** [comment]
I would like to work on this

**Comment by nandiniiiiiiii** [comment]
i would also like to work on this issue.

**Comment by anshikasrivastava17** [comment]
Assigned to all three. Whosoever raises the PR first with accuracy will be allotted the points.

**Comment by anshikasrivastava17** [comment]
Both of you raised the PR at the almost same time. But [Saga690](url) added the backend commit and file later. So I will be merging the PR raised by [ParthDhavan04](url). Keep up the contributions!
