### ISSUE TITLE
Create Comic Page

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#10]
Purpose: Interface for users to create their custom comics.

Features:
- Input fields for story text or keywords
- Options to select comic style (anime, traditional, etc.)
- Button to generate dialogues and images
- Preview section for the generated comic
- Email input field for comic book delivery

**Comment by ParthDhavan04** [comment]
i would like to work on this.

**Comment by Saga690** [comment]
Do you have the design?

**Comment by ParthDhavan04** [comment]
I would like to work on this.

**Comment by anshikasrivastava17** [comment]
assigned to both ! @Saga690 design is in discord channel
