### ISSUE TITLE
My Comics Page

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#11]
Purpose: Display all comics created by the user.

Features:
- Thumbnails of the comics
- Options to view, edit, or delete comics
- Button to create a new comic which redirects to generate comic page

**Comment by adx04** [comment]
@anshikasrivastava17 can i work on this issue?
please guide me a little about in which folder i should work and what kind of framework you would like me to use?

**Comment by anshikasrivastava17** [comment]
I m not assigning this issue rn bcoz there's nothing to work upon here till the comics are ready. Once we have that then u can work on display

**Comment by adx04** [comment]
hello @anshikasrivastava17 ....are the comics ready or maybe can i help with them?

**Comment by rampantvoid** [comment]
@anshikasrivastava17 i would like to work on this

**Comment by anshikasrivastava17** [comment]
> hello @anshikasrivastava17 ....are the comics ready or maybe can i help with them?

no they arent ready yet , u can assist with other issues surely. Once the comics are ready will def ping you!

**Comment by ParthDhavan04** [comment]
I would like to work on this.

**Comment by anshikasrivastava17** [comment]
I have thought that we will no longer have this page because not much point is being served since the PDFs are anyway getting delivered to the user's email. Same goes for view in browser page. Instead we can have another page, regarding which will create an issue soon.
