### ISSUE TITLE
Create Feedback Page

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#12]
Purpose: Allow users to provide feedback on their experience.
Features:
Input fields for feedback text , Rating system (e.g., stars) , Submit button
Display previous reviews

**Comment by Saga690** [comment]
Can you provide the design?

**Comment by adx04** [comment]
@anshikasrivastava17 i would like to work on this issue!

**Comment by ParthDhavan04** [comment]
I would like to work on this issue.
