### ISSUE TITLE
Login and SignUp Page Connection with MongoDB

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#13]
Connect to DB
Create a folder connectDB in backend and a file connect.js inside it

**Comment by shradiphylleia** [comment]
would like to take this up but need clartiy-do you need me to create the schema and implement user authentication using say(JWT) and secure the password using say(bcrypt)

**Comment by anshikasrivastava17** [comment]
I have not assigned this issue yet, and no contributions without assigning will be counted

**Comment by shradiphylleia** [comment]
when will this be assigned?

**Comment by anshikasrivastava17** [comment]
Once the login and signup pages are ready, this shall be assigned

**Comment by ParthDhavan04** [comment]
Now that we are done with login and signup can i be assigned this?

**Comment by shradiphylleia** [comment]
pls assign.

**Comment by anshikasrivastava17** [comment]
yes both can work on it now
