### ISSUE TITLE
Integrate frontend and backend

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#14]
Integrate frontend and backend for login procedure and check for authentication

**Comment by Saga690** [comment]
Can I work on this?

**Comment by anshikasrivastava17** [comment]
First I want the login page issue to be solved, then this shall be assigned to you

**Comment by ParthDhavan04** [comment]
Can i work on this now?

**Comment by shradiphylleia** [comment]
pls assign

**Comment by anshikasrivastava17** [comment]
yes guys y'all can work on it but first solve #46  . If you do both will give points for both
