### ISSUE TITLE
Dialogue Generation API Endpoint

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#15]
Create API endpoints in the Express server to interact with Gemini AI or ChatSonic API etc for generating dynamic dialogues based on user-provided scripts in the 'Generate Comic' page

**Comment by ParthDhavan04** [comment]
i want to work on this but i need more clarity.

**Comment by anshikasrivastava17** [comment]
connect on discord

**Comment by ParthDhavan04** [comment]
i would like to work on this issue.

**Comment by anshikasrivastava17** [comment]
assigned

**Comment by shradiphylleia** [comment]
would like to work on this.
