### ISSUE TITLE
Overlaying Dialogues and Images on Canvas

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#17]
The output images should be saved in the backend folder and overlay api should be called on clicking the 'click here to craft your comic' button

**Comment by rampantvoid** [comment]
hi can i be assigned to this issue

**Comment by ParthDhavan04** [comment]
I would like to take up this issue.

**Comment by anshikasrivastava17** [comment]
assigned to both
