### ISSUE TITLE
 Delivery of Comic PDF

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#18]
Use module ( like NodeMailer) to send the generated comic PDF to the user's email. Ensure the email delivery is reliable and secure.

**Comment by Saga690** [comment]
Would like to work on this

**Comment by anshikasrivastava17** [comment]
Once the comics are ready, then you can work on delivery

**Comment by ParthDhavan04** [comment]
i would like to work on this

**Comment by anshikasrivastava17** [comment]
Assigning to both. Added the creds in the resources on discord
