### ISSUE TITLE
Create a Favicon

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#2]
Design and integrate a favicon

**Comment by Saga690** [comment]
Can we use favicon generators? or we have to design it using canva/figma?

**Comment by anshikasrivastava17** [comment]
Yes you may use generators although it is recommended that you make everything from scratch for learning purpose

**Comment by Saga690** [comment]
I would like to work on this

**Comment by anshikasrivastava17** [comment]
Assigned!

**Comment by Saga690** [comment]
Created a PR
