### ISSUE TITLE
Fix deprecation warnings and vulnerabilities

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#26]
multiple deprecation warnings and vulnerabilities occuring when running npm install. set up plugins and config files

**Comment by ParthDhavan04** [comment]
I have solved this issue.

**Comment by ParthDhavan04** [comment]
Can it be assigned to me and should i raise the PR?

**Comment by anshikasrivastava17** [comment]
Yes please do the needful

**Comment by ParthDhavan04** [comment]
Just a sec.
