### ISSUE TITLE
Create a low-fidelity wireframe for the project  

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#4]
- It must have login/logout and sign-up functionality.
- Home Page 
- Dashboard for creating comics and asking user prompts for storyline, theme etc. and an email input box for delivering the generated PDF
- Feedback
- Gallery for viewing all the comics created or saved by the user.
- Any other custom feature you find relevant

**Comment by ParthDhavan04** [comment]
Hi, I would like to take up this issue.

**Comment by rampantvoid** [comment]
Hi can you assign this issue to me

**Comment by anshikasrivastava17** [comment]
yes assigned
