### ISSUE TITLE
Create a high-fidelity wireframe for the project  

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#5]
Creating a **high-fidelity wireframe** will provide a clear visual understanding of the interface layout, components, and interactions.
Use **Figma** or any other tool you find relevant for the task. 

1. Landing Page:
A clean and welcoming interface introducing users to our application's purpose and features. It should display the user's profile picture, name, interests and other details.

2. User Registration and Login:
Intuitive forms for user registration and login with input fields for username, email, and password. Include appropriate validation and error messages.

3. Dashboard:
To ask user email, story prompts etc and help the user generate the comic book.

4. Gallery:
To display all the comics created by the user.

5. Feedback:
Ask for user feedback and display other user's review as well. It could employ 5- star rating system or any other prevalent mechanism.

**Comment by ParthDhavan04** [comment]
Hi, I would like to take up this issue.

**Comment by anshikasrivastava17** [comment]
Assigned!
