### ISSUE TITLE
Revamp generate comic page

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#57]
<b> Alongwith existing input fields, </b> add field to take character description from the user.
The number of characters allowed should be maximum of 3 in a dropdown. As the user selects the number, 2 input fields should appear 1) Name
2) Character Description 
(Both these fields should be as many times as the number of characters is specified)

Add options for scenes' description to be taken from the user with a '+' sign next to it to increase the input as many times needed

Add two buttons 
1) To download the generated images
2) To preview the generated images

The whole page should look neat and decluttered.

**Comment by ParthDhavan04** [comment]
can i work on this?

**Comment by anshikasrivastava17** [comment]
assigned

**Comment by rampantvoid** [comment]
@anshikasrivastava17 hi i would like to work on this
