### ISSUE TITLE
Setup Login Page 

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#6]
Create a login page with email and password fields.

**Comment by nandiniiiiiiii** [comment]
hello ma'am I would like to work in this issue. I have worked in React and also understand backend and data base.

**Comment by anshikasrivastava17** [comment]
sure @nandiniiiiiiii I will be assigning this issue once we are done with the UI. For now if you want you can work on issue #4

**Comment by nandiniiiiiiii** [comment]
ok, so If I want to work on issue #4, do I have to work on Figma or what...??

**Comment by KhushiJain2004** [comment]
I would like to work on this!

**Comment by anshikasrivastava17** [comment]
@KhushiJain2004 do you want issue #4 ?

**Comment by KhushiJain2004** [comment]
No , i was asking about issue #6

**Comment by anshikasrivastava17** [comment]
> No , i was asking about issue #6

ya so as I mentioned before, I will assign this once we have the UI. If you wish you can work on the UI and then take up this issue or wait for a while till I assign it to you

**Comment by ParthDhavan04** [comment]
I want to work on this as well.

**Comment by anshikasrivastava17** [comment]
@nandiniiiiiiii @KhushiJain2004 @ParthDhavan04 assigning it to all 3. Whosoever does it first with the page closest to the UI will get the points. Please refer UI from the discord channel
