### ISSUE TITLE
Implement Character tab 

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#64]
1) Add a dropdown to choose for a maximum of 3 characters
2) Depending upon the dropdown, field rows for name and description should appear conditionally
3) Add a button to save character details
4) It should appear only in the 2nd tab on selection and not disrupt any other tab activity
5) Scroller should be functional if necessary

**Comment by ParthDhavan04** [comment]
Would like to work on this.

**Comment by anshikasrivastava17** [comment]
assigned
