### ISSUE TITLE
Prompt Setup

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#68]
Take character name input and description from the user. Take scene description and in the entire scene description wherever the name of the character appears, match the strings and replace that character name in the scene by the description of the character. Ensure that it works across all scenes for each character name.

**Comment by ParthDhavan04** [comment]
can i work on this?

**Comment by rampantvoid** [comment]
would like to work on this

**Comment by anshikasrivastava17** [comment]
Assigned to both @rampantvoid @ParthDhavan04
