### ISSUE TITLE
Setup Sign Up Page

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#7]
Create a registration page with fields for name, email, password, gender, username, profile picture (set as optional field).

**Comment by Lavanya-glitch** [comment]
i would like to work on this

**Comment by nandiniiiiiiii** [comment]
Hello ma'am pls allow me to work on this issue.

**Comment by AngadDogra** [comment]
hey can i be assigned to this

**Comment by ParthDhavan04** [comment]
Can i be assigned  to this issue?

**Comment by adx04** [comment]
hey @anshikasrivastava17 i would like to work on this issue!
(please mention the tech stack to be used as well or any key suggestions)

**Comment by anshikasrivastava17** [comment]
Assigning it to all of you. Whosoever does it first with closest design to UI wins the points. Please refer UI from discord channel

**Comment by adx04** [comment]
@anshikasrivastava17  i am not able to find any refrence in the discord channel. Can you please share it there or maybe here

**Comment by anshikasrivastava17** [comment]
> @anshikasrivastava17 i am not able to find any refrence in the discord channel. Can you please share it there or maybe here

@adx04 please check #resources on discord for comic craft project. If u are still unable to find it ping me on discord
