### ISSUE TITLE
Create the home page 

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#8]
Purpose: Provide users with access to their account information and actions.

Features:
User profile information with option to upload profile picture 
Navigation links to different functionalities (Generate Comic, My Comics Gallery etc)
Overview of recent activities or creations

**Comment by nandiniiiiiiii** [comment]
I would like to work on this issue.

**Comment by ParthDhavan04** [comment]
I would also like to work on this issue.

**Comment by anshikasrivastava17** [comment]
assigned to both

**Comment by Archisha-Dhyani** [comment]
i would like to work on this issue
