### ISSUE TITLE
Combine storyline and scene data for prompt and restructure tabs

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#81]
For gemini API, currently prompt is set to take question. Modify it to take both storyline and scenes before getting processed. The dialogues should be generated scene wise and there should be a clear demarcation for where the dialogue begins and ends.

Change the order in which tabs appear on generate page-
1) Characters
2) Scenes
3) Storyboard

**Comment by ParthDhavan04** [comment]
Would like to work on this.

**Comment by anshikasrivastava17** [comment]
assigned
