### ISSUE TITLE
Dialogue extraction from generated API Response

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#85]
Make an array for dialogues scene wise by extracting dialogues from generated API response paragraph. Generated paragraph has markers for beginning and end of each scene that have to be used. Each index of the array should have each dialogue as the index value.

**Comment by ParthDhavan04** [comment]
can i work on this

**Comment by anshikasrivastava17** [comment]
assigned
