### ISSUE TITLE
Components of Navbar and Footer 

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#9]
Within src\components create the components of navbar and footer. 

Navbar must contain links to Home page, Comic generation page, Gallery, Reviews and have a logout button.

Design a footer you find relevant as per the project.

**Comment by Vaishnavi024** [comment]
Hi I want to work on this issue. The navbar one.

**Comment by reallywasi** [comment]
Hii 
I'd like this issue to be assigned.

**Comment by anshikasrivastava17** [comment]
Hello @Vaishnavi024 @reallywasi i will be assigning these issues once the UI is done! If you wish you can contribute in the UI

**Comment by ParthDhavan04** [comment]
i would like to work on this.

**Comment by anshikasrivastava17** [comment]
Assigned to all! Check for the UI in the discord channel

**Comment by Saga690** [comment]
Can I work on this too?
