### ISSUE TITLE
Fix UI and redirection

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#95]
1) For signup page
- Add image of the line from figma file to the left and right of OR button instead of hardcoded text (refer login page)
- Change the color of the buttons and text as per UI

2) For login page add border effect, font weight etc necessary styling to make it better

Redirection to be added in generate.js
- From character tab to scenes tab once the character info is saved
- From scenes tab to storyboard once the scenes are processed

**Comment by ParthDhavan04** [comment]
can i work on this

**Comment by anshikasrivastava17** [comment]
assigned
