### ISSUE TITLE
Signup Flow and Private Component

### ISSUE THREAD

**Issue by anshikasrivastava17** [upes-open/OSoC-24-Comic-Craft#97]
- Set username in local storage and clear it at the time of logout
- Ensure logout with a popup confirmation with "OK" and "cancel". Logout should redirect to landing page.
- Navbar should toggle between signup and logout buttons depending on user is logged in/out.
- Set up **private component**, that is pages like generate feedback etc should not be open if user is not logged in. Once the user is logged in pages like signup, login should not open.

**Comment by ParthDhavan04** [comment]
can i work on this

**Comment by anshikasrivastava17** [comment]
assigned
